"""Project creation scaffolding for `tak new project`."""

from __future__ import annotations

from typing import TYPE_CHECKING

from tak.scaffold.agents_md import generate_agents_md
from tak.scaffold.detect import TechStack, detect_tech_stack
from tak.scaffold.rules import generate_rules
from tak.scaffold.skills import generate_skill_md
from tak.setup._cmd import has_command, run_cmd

if TYPE_CHECKING:
    from pathlib import Path


def _git_init(project_dir: Path) -> bool:
    """Run ``git init`` inside *project_dir*.

    Args:
        project_dir: Target directory for the git repository.

    Returns:
        True when the command succeeds; False otherwise.
    """
    if not has_command("git"):
        return False
    try:
        result = run_cmd("git", "init", str(project_dir))
        return result.returncode == 0
    except (FileNotFoundError, OSError):
        return False


def _write_readme(project_dir: Path, name: str, description: str) -> None:
    """Write a minimal README.md to *project_dir*.

    Args:
        project_dir: Target directory.
        name: Project name.
        description: One-sentence project description.
    """
    content = f"# {name}\n\n{description}\n"
    (project_dir / "README.md").write_text(content, encoding="utf-8")


def _write_gitignore(project_dir: Path, stack: TechStack) -> None:
    """Write a basic .gitignore appropriate for the detected *stack*.

    Args:
        project_dir: Target directory.
        stack: The detected tech stack.
    """
    lines: list[str] = ["# Generated by tak new project", ""]

    if stack.language == "Python":
        lines += [
            "__pycache__/",
            "*.py[cod]",
            "*.egg-info/",
            "dist/",
            "build/",
            ".venv/",
            "venv/",
            ".mypy_cache/",
            ".ruff_cache/",
            ".pytest_cache/",
            "*.egg",
            "",
        ]
    elif stack.language in ("JavaScript", "TypeScript"):
        lines += [
            "node_modules/",
            "dist/",
            "build/",
            ".next/",
            ".nuxt/",
            "coverage/",
            "*.log",
            "",
        ]
    elif stack.language == "Rust":
        lines += ["target/", "Cargo.lock", ""]
    elif stack.language == "Go":
        lines += ["bin/", "vendor/", "*.test", ""]

    lines += [".DS_Store", ".env", "*.env.local", ""]
    (project_dir / ".gitignore").write_text("\n".join(lines), encoding="utf-8")


def create_project(
    name: str,
    parent_dir: Path,
    description: str = "",
    language: str | None = None,
    framework: str | None = None,
    include_skill: bool = False,
    git: bool = True,
) -> dict[str, object]:
    """Create a new project skeleton under *parent_dir/name*.

    Generates AGENTS.md, .cursor/rules/, README.md, and .gitignore.
    Optionally adds SKILL.md and runs ``git init``.

    Args:
        name: Project directory name and display name.
        parent_dir: Directory in which to create the new project folder.
        description: Short project description.
        language: Override the detected language (e.g. ``"Python"``).
        framework: Optional framework name (e.g. ``"FastAPI"``).
        include_skill: When True, also generate a SKILL.md.
        git: When True, run ``git init`` in the new project directory.

    Returns:
        A summary dict with keys ``project_dir``, ``files_created``,
        ``git_initialized``, and ``stack``.

    Raises:
        FileExistsError: When the target directory already exists.
    """
    project_dir = parent_dir / name
    if project_dir.exists():
        raise FileExistsError(f"Directory '{project_dir}' already exists.")

    project_dir.mkdir(parents=True)

    if language:
        stack = TechStack(language=language, framework=framework)
    else:
        stack = detect_tech_stack(project_dir)

    desc = description or f"{name} project."
    files_created: list[str] = []

    generate_agents_md(
        project_name=name,
        output=project_dir / "AGENTS.md",
        project_description=desc,
        force=False,
        stack=stack,
    )
    files_created.append("AGENTS.md")

    rules_dir = project_dir / ".cursor" / "rules"
    created, _ = generate_rules(rules_dir=rules_dir, stack=stack)
    for f in created:
        files_created.append(f".cursor/rules/{f}")

    _write_readme(project_dir, name, desc)
    files_created.append("README.md")

    _write_gitignore(project_dir, stack)
    files_created.append(".gitignore")

    if include_skill:
        generate_skill_md(
            skill_name=name,
            description=desc,
            output=project_dir / "SKILL.md",
            force=False,
        )
        files_created.append("SKILL.md")

    git_initialized = False
    if git:
        git_initialized = _git_init(project_dir)

    return {
        "project_dir": project_dir,
        "files_created": files_created,
        "git_initialized": git_initialized,
        "stack": stack,
    }
